shared:
    environment:
        DOCKER_REPO: wahapo/screwdriver-test

jobs:
    docker-publish:
        requires: ~commit
        template: sd/dind@latest
        steps:
            - init: |
                date -u +"%Y%m%d-%H%M%S" > VERSION
                sleep 2
                docker login --username $DOCKER_REGISTRY_USER --password $DOCKER_REGISTRY_TOKEN
                sleep 2
                mkdir -p ~/.docker/cli-plugins/
                wget https://github.com/docker/buildx/releases/download/v0.7.1/buildx-v0.7.1.linux-amd64 -O ~/.docker/cli-plugins/docker-buildx
                chmod a+x ~/.docker/cli-plugins/docker-buildx
                sleep 2
                docker context create mycontext
                docker buildx create mycontext --name mybuilder --use
                docker buildx inspect --bootstrap
                docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            - build: |
                docker buildx build --platform linux/arm64 --push -t $DOCKER_REPO:latest .
            - publish: |
                echo "skip"
